version: '3.7'
services:
  bento:
    container_name: new-bento
    build: .
    restart: always
    ports:
      - "8010:3000"
    environment:
      SIERRA_API_KEY: Passkey
      BROWZINE_API_KEY: Passkey
